webapp:
    build: webapp
    environment:
        - SAMPLES_TCP_URL=datamining:6969
    ports:
        - "3030:3030"
    links:
        - datamining

datamining:
    build: datamining
    environment:
        - SAMPLES_TCP_URL=*:6969
